"""Синхронизация с текущим состоянием

Revision ID: 72636e798bc5
Revises: 8c123
Create Date: 2025-05-11 17:24:47.392666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72636e798bc5'
down_revision: Union[str, None] = '8c123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # SQLite не поддерживает ALTER COLUMN, а поля уже есть — пропускаем
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_scan', sa.Column('filepath', sa.VARCHAR(length=255), nullable=False))
    op.alter_column('project', 'responsible_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('project', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('project', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
